### ISSUE TITLE
Item does not scale back to normal size on drop

### ISSUE THREAD

**Issue by andryak** [mochixuan/react-native-drag-sort#44]
When an item is dragged it scales up but when it is released it does not scale back to normal (see attached screenshot).

This seems due to an error in the endTouch method, which is responsible to scale the item back to its normal size. This method starts the animation to scale the item back but then calls the changePosition method which triggers a re-render and interrupts the animation.

Please, review MR #43 which fixes this.

![Screenshot 2019-11-04 at 16 18 54](https://user-images.githubusercontent.com/1419399/68134709-ccb69700-ff22-11e9-9159-430388258a6b.png)

**Comment by mochixuan** [comment]
Animations in the development environment will be compared to the card, and frame dropping may occur. You can test if there is no recovery under the release. This should not happen according to the code logic. You can test if it will appear after packaging.
Because the animation has 100ms. If you wait for the animation to finish, you may get stuck.

**Comment by leelandclay** [comment]
When I was testing, I noticed this problem and was able to get it to fail every time on an emulator by moving the mouse while the animation was finishing. While this won't happen on an actual device, I found it weird and my OCD required it to go back to normal.
Thanks for the fix @andryak  I added it locally and it fixed the problem.
