### ISSUE TITLE
DragSortableView Does not work inside ScrollView

### ISSUE THREAD

**Issue by priyanshrastogi** [mochixuan/react-native-drag-sort#63]
```js
<ScrollView srcollEnabled={this.state.scrollEnabled}>
    <DragSortableView
         dataSource={this.state.profilePic}
         parentWidth={Dimensions.get('window').width}
         childrenWidth= {width}
         childrenHeight={width}
         marginChildrenTop={20}
         marginChildrenLeft={10}
         marginChildrenRight={10}
         onDragStart={() => this.setState({scrollEnabled: false})}
         onDragEnd={() => this.setState({scrollEnabled: true})}
         fixedItems={this.getFixedItems()}
         onDataChange={(data) => this.setState({profilePic: data})}
         onClickItem={this.onItemPress}
         keyExtractor={(item, index)=> `${index}_${parseInt(Math.random()*10000)}`}
         renderItem={this.renderProfilePicture}
    />
</ScrollView>
```

DragSortableView works fine if it is not inside ScrollView, but inside ScrollView when I call this.setState() onDragStart, screen freezes and it cannot be dragged.

**Comment by mochixuan** [comment]
A brief look at your code is no problem. You can copy my DEMO and modify it to see where the problem is.
You can refer to the manual DEMO slide: https://github.com/mochixuan/react-native-drag-sort/blob/master/Example/app/container/OneRowsPage.js
You can also refer to the DEMO of automatic sliding: https://github.com/mochixuan/react-native-drag-sort/blob/master/Example/app/container/AutomaticSlidingOnePage.js

**Comment by yuyanghh** [comment]
<ScrollView **srcollEnabled**={this.state.scrollEnabled}>

at line one
fix the typo and you should be good~
